services:
  - type: web
    name: minisocialmedia
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn socialmedia.wsgi:application"
    branch: master
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DISABLE_COLLECTSTATIC
        value: "0"
      - key: PYTHON_VERSION
        value: "3.12.3"
      - key: DATABASE_URL
        fromDatabase:
          name: minisocialmedia-db
          property: connectionString
      - key: RENDER_EXTERNAL_HOSTNAME
        sync: false  # Let Render auto-inject this

databases:
  - name: minisocialmedia-db
    plan: free
    databaseName: socialmedia
    user: socialmedia_user