services:
  - type: web
    name: minisocialmedia
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn socialmedia.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_mVx1lXQ3sjrp@ep-billowing-bread-a81l0fml-pooler.eastus2.azure.neon.tech/neondb?sslmode=require # PASTE YOUR ACTUAL URL HERE
      - key: DISABLE_COLLECTSTATIC
        value: "0"